Added Edit Categories
MaharshM/to-do-application pull request #29
Opened 2022-07-01 06:47 UTC by MaharshM

2022-07-01 10:42 UTC, abbasali requested changes

2022-07-01 10:42 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +        $categoryId = $id;
This is absolutely redundant. What's the purpose of creating a new variable here?

2022-07-01 10:42 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +        $description = Category::find($id)->description;
You don't need to set fields separately for view. Set the entire `$category` object for view.

2022-07-01 10:42 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +    public function update(Request $request, $id)
Use Route model binding.

2022-07-01 10:42 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +            $categoryNew = Category::find($id)->update(
This will change once we use Route model binding.

2022-07-01 10:42 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +
Validations? Same validation rules there were used in Create. In fact, same Request class should be used.

2022-07-01 11:02 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +        $description = Category::find($id)->description;
done.

2022-07-01 11:10 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +
added.

2022-07-01 11:27 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +            $categoryNew = Category::find($id)->update(
done.

2022-07-01 11:27 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +    public function update(Request $request, $id)
done.

2022-07-01 11:36 UTC, abbasali requested changes

2022-07-01 11:36 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +    public function update(CreateCategoryRequest $request, Category $category)
Since we are now using a common request class for both create and update - we need to change its name to be a common one. So rename it to SaveCategoryRequest which is common term for create and update.

2022-07-01 11:36 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +        $rules = array(
What is the purpose of this array? Where is `$rules` used?

2022-07-01 11:36 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +            $category->update(
Use the following code to update the category.

```php
$category->name = $data['name'];
$category->description = $data['description'];
$category->save();
```

2022-07-01 11:36 UTC, abbasali commented on resources/views/category/edit.blade.php
> +                    <x-input id="name" class="block mt-1 w-full" type="name" name="name" value="{{ $category->name }}" required autofocus />
Did you see what happens when there is a validation error? The data in the form should be pre-filled with what was submitted. In other words, when you submit a category name which already exists then this form should come prefilled with that name and not from database value.

2022-07-01 11:43 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +    public function update(CreateCategoryRequest $request, Category $category)
done.

2022-07-01 11:46 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +            $category->update(
done.

2022-07-01 11:47 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +    public function update(CreateCategoryRequest $request, Category $category)
done.

2022-07-01 11:50 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +        $rules = array(
was previously using it for edit validation. Removed it now.

2022-07-04 04:36 UTC, MaharshM commented on resources/views/category/edit.blade.php
> +                    <x-input id="name" class="block mt-1 w-full" type="name" name="name" value="{{ $category->name }}" required autofocus />
done.

2022-07-04 09:29 UTC, abbasali requested changes

2022-07-04 09:29 UTC, abbasali commented on app/Policies/CategoryPolicy.php
> +        return $category->user_id == Auth::user()->id;
This is wrong. The current logged in user is already present in `$user` argument. Use that and not `Auth::user()`.

2022-07-04 09:33 UTC, MaharshM commented on app/Policies/CategoryPolicy.php
> +        return $category->user_id == Auth::user()->id;
done.

2022-07-04 10:02 UTC, abbasali requested changes

2022-07-04 10:02 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +        $this->authorize('view' , $category);
We are editing a category so the policy method name should be `update` and not `view`.

2022-07-04 10:02 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +        $this->authorize('view' , $category);
We are editing a category so the policy method name should be `update` and not `view`.

2022-07-04 10:02 UTC, abbasali commented on app/Http/Controllers/CategoryController.php
> +        $this->authorize('view' , $category);
There should be no space before `,` in method parameters.

2022-07-04 10:08 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +        $this->authorize('view' , $category);
done.

2022-07-04 10:08 UTC, MaharshM commented on app/Http/Controllers/CategoryController.php
> +        $this->authorize('view' , $category);
done.

2022-07-04 10:25 UTC, abbasali approved these changes

2022-07-04 10:26 UTC, merged