Listing Todos
MaharshM/to-do-application pull request #32
Opened 2022-07-06 09:45 UTC by MaharshM

2022-07-08 12:10 UTC, abbasali requested changes

2022-07-08 12:10 UTC, abbasali commented on app/Http/Controllers/AttachmentController.php
> +        $todo = DB::table('todos')->where('id', $attachment->todo_id)->get()->first();
Use Attachment and Todo relationship (eloquent) to get the Todo.

2022-07-08 12:10 UTC, abbasali commented on app/Http/Controllers/AttachmentController.php
> +        $deleteAttachment = Attachment::find($attachment->id);
Why finding attachment again? We already have it in `$attachment`.

2022-07-08 12:10 UTC, abbasali commented on app/Http/Controllers/AttachmentController.php
> +        return view('todo.show', compact('todo', 'attachments'));
Simply redirect back to `todos.show` route. No need to render the view here. Redirect back.

2022-07-08 12:10 UTC, abbasali commented on app/Http/Controllers/TodoController.php
> +    public function show(Category $category, Todo $todo)
Why passing category? Just Todo should be enough.

2022-07-08 12:10 UTC, abbasali commented on app/Policies/AttachmentPolicy.php
> +        $todo = Todo::find($attachment->todo_id);
Why not using relation methods to find the todo?

2022-07-08 12:10 UTC, abbasali commented on app/Policies/AttachmentPolicy.php
> +        return $todo->user_id == Auth::user()->id;
I had said this earlier as well, you should not use `Auth::user()` in policies. You already get the current user in the `$user` argument.

2022-07-08 12:52 UTC, MaharshM commented on app/Http/Controllers/AttachmentController.php
> +        $todo = DB::table('todos')->where('id', $attachment->todo_id)->get()->first();
done.

2022-07-08 12:53 UTC, MaharshM commented on app/Http/Controllers/AttachmentController.php
> +        $deleteAttachment = Attachment::find($attachment->id);
corrected

2022-07-08 13:09 UTC, MaharshM commented on app/Policies/AttachmentPolicy.php
> +        return $todo->user_id == Auth::user()->id;
sorry about this. didnt save before pushing

2022-07-08 13:32 UTC, MaharshM commented on app/Http/Controllers/AttachmentController.php
> +        return view('todo.show', compact('todo', 'attachments'));
done.

2022-07-09 14:46 UTC, abbasali requested changes

2022-07-09 14:46 UTC, abbasali commented on app/Http/Controllers/TodoController.php
> +        $attachments = DB::table('attachments')->get();
Again, we should always use relationship methods and not `DB::table()`. The count of attachments can be fetched in the same query where you are finding all todos using the `withCount()` method.

2022-07-09 14:46 UTC, abbasali commented on app/Http/Requests/StoreCategoryRequest.php
> +<?php
Create/store category was already done then why do we need this request class?

2022-07-09 14:46 UTC, abbasali commented on routes/web.php
> +Route::get('/attachment/{attachment}', [AttachmentController::class, 'destroy'])->name('attachment.destroy');
Delete should use `Route::delete()` method. Not `get()`.

2022-07-10 08:30 UTC, MaharshM commented on app/Http/Controllers/TodoController.php
> +    public function index(Category $category, Todo $todo)
by that logic i can just skip getting `$todo` altogether and just pass the `$category` in the `todo.index` view here, getting the todo from category model object itself.

2022-07-10 08:31 UTC, MaharshM commented on app/Http/Controllers/TodoController.php
> +        $attachments = DB::table('attachments')->get();
got it. was having problems understanding relationship methods. now clear. changing everywhere

2022-07-10 08:47 UTC, MaharshM commented on app/Http/Requests/StoreCategoryRequest.php
> +<?php
it was causing clashes in the `update` method of the `CategoryController` as for updating a category we need to ignore the category that was already present and when there were 0 categories, the same rule for create category throws an error.

2022-07-10 17:50 UTC, MaharshM commented on app/Http/Controllers/TodoController.php
> +        $attachments = DB::table('attachments')->get();
done.

2022-07-10 17:50 UTC, MaharshM commented on routes/web.php
> +Route::get('/attachment/{attachment}', [AttachmentController::class, 'destroy'])->name('attachment.destroy');
done.

2022-07-11 04:29 UTC, abbasali requested changes

2022-07-11 04:29 UTC, abbasali commented on app/Http/Controllers/AttachmentController.php
> +    {
No authorization for download? Anyone can download any other user's files?

2022-07-11 04:29 UTC, abbasali commented on app/Http/Requests/StoreCategoryRequest.php
> +<?php
In that case a simple `if` / `else` in the `rules()` method of that class would have worked. If the current request is for create, then the rule would be different for category name and if the current request is edit then different. Try doing it in a single request class.

2022-07-11 04:29 UTC, abbasali commented on routes/web.php
> +Route::resource('attachment', AttachmentController::class);
`Route::resource()` will create a lot of resources and not just `delete`. You should add `->only(['deleted'])` at the end so that it only generates the delete resource.

2022-07-11 04:34 UTC, MaharshM commented on app/Http/Controllers/AttachmentController.php
> +    {
done.

2022-07-11 05:10 UTC, MaharshM commented on app/Http/Requests/StoreCategoryRequest.php
> +<?php
resolved.

2022-07-11 05:15 UTC, MaharshM commented on routes/web.php
> +Route::resource('attachment', AttachmentController::class);
done

2022-07-11 05:25 UTC, abbasali requested changes

2022-07-11 05:25 UTC, abbasali commented on app/Policies/AttachmentPolicy.php
> +        return $todo->user_id == $user->id;
`return $attachment->todo->user_id == $user->id`

2022-07-11 05:50 UTC, MaharshM commented on app/Policies/AttachmentPolicy.php
> +        return $todo->user_id == $user->id;
done.

2022-07-11 05:57 UTC, abbasali requested changes

2022-07-11 05:57 UTC, abbasali commented on app/Http/Requests/SaveCategoryRequest.php
> +            $rules['name'][2] = "unique:categories,name,NULL,id,user_id,$user";
There is no need to add `[2]`. Just doing `[]` will properly add the value to `2` index.

2022-07-11 05:57 UTC, abbasali commented on app/Policies/AttachmentPolicy.php
> +        $this->view;
`view` is a method and it requires two params. Why are you not calling it as a method?

2022-07-11 06:03 UTC, MaharshM commented on app/Http/Requests/SaveCategoryRequest.php
> +            $rules['name'][2] = "unique:categories,name,NULL,id,user_id,$user";
done.

2022-07-11 06:03 UTC, MaharshM commented on app/Policies/AttachmentPolicy.php
> +        $this->view;
done

2022-07-11 06:07 UTC, abbasali approved these changes

2022-07-11 06:08 UTC, merged